### ISSUE TITLE
csv extractor problem

### ISSUE THREAD

**Issue by szikanova** [orientechnologies/orientdb-etl#100]
The csv extractor class is not recognized, therefore have to use row. Should at least update orientdb documentation to reflect this: http://orientdb.com/docs/2.1/Extractor.html

**Comment by robfrank** [comment]
Hi, I'm sorry, but documentation doesn't indicate that CSV extractor is available only from 2.1.4. I'll update asap. Take a look at the 2.1.4 and let me know if all it's working right.

**Comment by robfrank** [comment]
Documentation is fixed: https://github.com/orientechnologies/orientdb-docs/commit/f04304c1ee97661075c6eb9d18e7781d01e45d96
