### ISSUE TITLE
Add testing module

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb-etl#21]
It seems like every release breaks something here and there. It would be very useful if the ETL had a CI that ran tests. Customers (like myself) could then add tests with the following files:
1. `setup.sql` - set up the schema for the ETL
2. `CLASS.json` - config files for every class
3. `CLASS.data` - mock JSON data files for every class
At a very basic level, the test could just ensure that the ETL completed without error. At a more useful level, the test could also run queries and compare the results to what is expected.

**Comment by garrett-gottlieb** [comment]
@laa I think this is done. If so, we can close this.

**Comment by tglman** [comment]
mvn clean install is not running  the tests, so is it jenkins but we are not really running tests in jenkins, i'll reopen this.

**Comment by stokito** [comment]
As I see [orientdb-etl in Jenkins](http://helios.orientechnologies.com/job/orientdb-etl/) tests are runing now.
