### ISSUE TITLE
csv transformation to multi vertexes

### ISSUE THREAD

**Issue by plessmann** [orientechnologies/orientdb-etl#41]
Is it possible to transform one row of one csv file (orderitems.csv) to different vertexes in ODB?
In my source document database there are no relations and there is only one single collection, so the values of the fields are stored in a redundant way.
So, some fields (e.g. "brand" or "model") should be stored as an separate Vertex in my ODB schema and should not be stored as a simple Vertex property in the class specified in transformers.vertex.class = Items.

The ordritems.csv format looks something like that:

id,order,name,price,brand,model

and sould become something like that:
Order (rid,id, link to Items)
Items (rid,name, price, link to Brand, link to Model)
Brand (rid, title)
Model (rid, title)

I could not find any information about that in the documentation. Any ideas?

regards,
Lars

**Comment by lvca** [comment]
We don't have an easy solution for this case. The best is calling `command` transformer that execute a "create edge" command.

**Comment by plessmann** [comment]
Sounds okay for me but can you post a little example? The Wiki is not very verbose about that function (http://www.orientechnologies.com/docs/last/orientdb-etl.wiki/Transformer.html#command) how to create an Edge between two Vertexes during storing a second Vertex if it still does not exist (to prevent duplicates).

**Comment by lvca** [comment]
@plessmann I think your use case it's pretty common. I'd like to improve the "edge" transformer with the ability to specify the fields to create. Something like:

```json
{
  "edge": {
    "lookup": "Customer.id",
    "joinFieldName": "customer",
    "fields": {
      "name: "$input.name",
      "surname: "$input.surname"
    }
  }
}
```

**Comment by plessmann** [comment]
Okay looks great. So I just have to wait for milestone 2.1 ?

**Comment by stokito** [comment]
+1 for this feature

**Comment by rajohn96** [comment]
would enabling a server side function call make this more straightforward? instead of a "vertex" or an "edge" or a "command" have a "function" choice, which has free reign to create whatever it needs, based on the data it is given. Or, can I already do this with the "command" transformer, simply calling the function that way?

**Comment by lvca** [comment]
Supported. Added the following test case
```
    process("{source: { content: { value: 'id,name,surname,friendSince,friendId,friendName,friendSurname\n0,Jay,Miner,1996,1,Luca,Garulli' } }, extractor : { row: {} },"
        + " transformers: [{csv: {}}, {vertex: {class:'V1'}}, "
        + "{edge:{unresolvedLinkAction:'CREATE',class:'Friend',joinFieldName:'friendId',lookup:'V2.fid',targetVertexFields:{name:'${input.friendName}',surname:'${input.friendSurname}'},edgeFields:{since:'${input.friendSince}'}}},"
        + "{field:{fieldNames:['friendSince','friendId','friendName','friendSurname'],operation:'remove'}}"
        + "], loader: { orientdb: { dbURL: 'memory:ETLBaseTest', dbType:'graph', useLightweightEdges:false } } }");

```
