### ISSUE TITLE
link transform unresolvedLinkAction is not executable

### ISSUE THREAD

**Issue by mudigal** [orientechnologies/orientdb-etl#43]
In file OLinkTransformer.java line 104, the if result!=null condition block is not terminated rightly, hence the else part of it is hiddent inside the if.

It goes this way - if(result!=null) {

                                       if(result==null){
                                      switch case for different options
                                      }
                             }

**Comment by lvca** [comment]
@mudigal why? inside switch evaluate the instanceof of result.

**Comment by lvca** [comment]
No response. Closing the issue
