### ISSUE TITLE
Remove example of ETL scenarios

### ISSUE THREAD

**Issue by stokito** [orientechnologies/orientdb-etl#44]
A directory [/src/main/resources](https://github.com/orientechnologies/orientdb-etl/tree/master/src/main/resources) contains example scenarios of usage ETL.
The problem is that they are packed in resulting JAR file of dependency.
I would like to propose split them to different repository like `etl-example-scenarios`

**Comment by stokito** [comment]
I decided to keep them alive, but make some integratiion tests from them
If someone interested here is my branch
https://github.com/stokito/orientdb-etl/tree/integration_tests

**Comment by robfrank** [comment]
This issue was moved to orientechnologies/orientdb#5167
