### ISSUE TITLE
NULL values and empty strings in cells

### ISSUE THREAD

**Issue by kaidzen** [orientechnologies/orientdb-etl#53]
For example:
We have a columns: `id,title,postid,text`
And our rows are: 
`1,,2,ololo` =>  Then field "title" should be parsed as null.
`1,"",2,ololo` => Then field "title" should be parsed as "" (empty string).
`1,NULL,2,ololo` and nulValue config option is `NULL` => Then field "title" should be parsed as null
`1,,2,ololo` and nulValue config option is `NULL` => Then field "title" should be parsed as "" (empty string)

**Comment by kaidzen** [comment]
Here I created some unit test to cover this cases. But cases:
`1,"",2,ololo`
`1,,2,ololo`
Are failed (testQuotedEmptyString and testNullValueInCellEmptyString)

**Comment by lvca** [comment]
Where are such test cases?

**Comment by profeg** [comment]
1,,2,ololo => field "title" should be parsed as null. - OCSVTransformerTest.java:239
1,"",2,ololo => field "title" should be parsed as "" (empty string). - OCSVTransformerTest.java:261
1,NULL,2,ololo and nulValue config option is NULL =>  field "title" should be parsed as null - OCSVTransformerTest.java:250

**Comment by lvca** [comment]
@profeg do you have such test cases?

**Comment by profeg** [comment]
Hi, I'm confused. Why you do not like the tests on this issue located in the file OCSVTransformerTest.java. Please explain your question in detail. 



     On Tuesday, May 12, 2015 7:52 PM, Luca Garulli <notifications@github.com> wrote:
   

 @profeg do you have such test cases?—

**Comment by lvca** [comment]
@profeg Sorry I just recognized they are on master branch, while I was on develop.

**Comment by lvca** [comment]
Ok, I've merged "develop" (2.1-SNAPSHOT) from master (2.0.9-SNAPSHOT). Thanks, test cases are here.

**Comment by lvca** [comment]
All test cases seems to pass. So is this issue closed?

**Comment by profeg** [comment]
Yes , I think it is closed.
 


     On Thursday, May 14, 2015 7:17 PM, Luca Garulli <notifications@github.com> wrote:
   

 All test cases seems to pass. So is this issue closed?—
