### ISSUE TITLE
Negative numbers represent as string

### ISSUE THREAD

**Issue by profeg** [orientechnologies/orientdb-etl#54]
Hi.
I write some test methods to testing  ```OCSVTransformer.java```. And find what negative numbers converts to DB like String type values.

**Comment by lvca** [comment]
WDYT about a PR?

**Comment by profeg** [comment]
I am  sorry, but canst you clarify your question?

**Comment by lvca** [comment]
I didn't see the PR (Pull Request). Now it's merged, thanks.

**Comment by profeg** [comment]
Thank you =)
