### ISSUE TITLE
 Import from RDBMS DB2 To Document DB OrientDB 

### ISSUE THREAD

**Issue by AntonSukhov** [orientechnologies/orientdb-etl#63]
In my database CU242176 DBMS OrientDB  version 2.0.7 is a table M_PERM:
PERM_DESC:string.
PERM_ID:integer not null;
PERM_NAME:string.
In my database CU242176 DBMS DB2 version 9.1 is a table  M_PERM of the same structure. In this table 14 rows.
With module Orientdb-ETL I did import the data. No errors, but there is no data in the table. While the table is created index on PERM_ID. Here is my config:
{
  "config":{
    "log": "debug"
  },
  "extractor" : {
    "jdbc": 
	{  "driver": "com.ibm.db2.jcc.DB2Driver",
       "url": "jdbc:db2://ITS-C:50000/CU242176",
       "userName": "metr",
       "userPassword": "**********",
       "query": "select PERM_DESC,PERM_ID,PERM_NAME from METR.M_PERM"
	}
  },
  "transformers":[
  ],
  "loader" : {
    "orientdb": {
      "dbURL": "plocal:c:/Program Files/orientdb-community-2.0.7/databases/CU242176",
      "dbUser": "admin",
      "dbPassword": "admin",
      "dbAutoCreate": false,
	  "standardElementConstraints": false,
      "tx":true,
	  "wal":false,
	  "batchCommit":1000,
      "dbType": "document",
	  "classes":[{"name": "M_PERM"}],
      "indexes": [{"class":"M_PERM", "fields":["PERM_ID:integer"], "type":"UNIQUE" }]
    }
  }
}
Log executed command (oetl config_Import_M_PERM_JDBC.json):
OrientDB etl v.2.0.7 (build @BUILD@) www.orientechnologies.com
[orientdb] DEBUG Opening database 'plocal:c:/Program Files/orientdb-community-2.0.7/databases/
CU242176'...

2015-04-29 14:39:34:562 WARNING {db=CU242176} segment file 'database.ocf' was not closed corre
ctly last time [OSingleFileSegment]BEGIN ETL PROCESSOR
[orientdb] DEBUG orientdb: found 0 documents in class 'null'
END ETL PROCESSOR
+ extracted 29 records (0 records/sec) - 29 records -> loaded 14 documents (0 documents/sec) T
otal time: 159ms [0 warnings, 0 errors]

How do I resolve this issue? For 14 lines loaded into my table.

**Comment by lvca** [comment]
Add 
```
"class": "M_PERM",
```

in loader block.
