### ISSUE TITLE
how to use customer support

### ISSUE THREAD

**Issue by sck2015** [orientechnologies/orientdb-etl#64]
hi, I'm at bloomberg, we just started our customer support agreement with you; could someone please call me at 609-279-4019 (US); I need guidance on loading a significant slew of relationships into orientdb, thanks, Sonu Khullar

**Comment by sck2015** [comment]
please advise how I can post some sample etl that is taking hours to run (again, edge centric and using sql in a "command" json directive) and is running out of memory, seems similar to an issue already posted in this chat, ideally in a private repository

**Comment by lvca** [comment]
@sck2015 please drop an email to support at orientdb dot com.
