### ISSUE TITLE
Perhaps we don't need the first command in the oetl.sh

### ISSUE THREAD

**Issue by idlesummerbreeze** [orientechnologies/orientdb-etl#65]
Hi all,

I copied the file oetl.sh to the directory bin/ in according to the readme and run it using ./bin/oetl.sh. this script run to the following error:

./bin/oetl.sh: line 26: cd: ./bin/..: No such file or directory
Error: Could not find or load main class com.orientechnologies.orient.etl.OETLProcessor 

I think, that we don't need the first command in the script, then everything will be fine!

Regards,
Yu Liu

**Comment by lvca** [comment]
I can't see that line. What version are you using?

**Comment by idlesummerbreeze** [comment]
I mean "cd `dirname $0`" in the oetl.sh. I have just checked out the sourcecode from https://github.com/orientechnologies/orientdb-etl

**Comment by robfrank** [comment]
This issue was moved to orientechnologies/orientdb#5166
