### ISSUE TITLE
csv etl (oetl.sh) authentication only works for "admin'+'admin'

### ISSUE THREAD

**Issue by zhuobao** [orientechnologies/orientdb-etl#66]
in version 2.0.10, authentication (role+password) works only when databases' admin role password is "admin", which is the default value. It does not depends if the input password match the set or not.

**Comment by lvca** [comment]
Could you share your JSON snippet?

**Comment by zhuobao** [comment]
I confirmed the finding by switching password back to "admin"+"admin" and it works again. By the way, I am talking about the community 2.0.10 version. 

Below is the categories.json for the openbeer dataset, it is almost the same with one provide by orientdb manual except the dbUser and dbPassword.


1 {
  2     "source": { "file": { "path": "/home/zbao/zworkfiles/projects/GraphVM/data/raw_data/openbeer/openbeerdb_csv/categories.csv" } },
  3     "extractor": { "row": {} },
  4     "transformers": [
  5         { "csv": {} },
  6         { "vertex": { "class": "Category2" } }
  7      ],
  8         "loader": {
  9         "orientdb": {
 10             "dbURL": "remote:localhost/openbeer",
 11             "dbUser": "admin",
 12             "dbPassword": "admin",
 13             "tx": false,
 14             "dbType": "graph",
 15             "classes": [
 16                 {"name": "Category2", "extends": "V"}
 17             ], "indexes": [
 18                 {"class":"Category2", "fields":["id:integer"], "type":"UNIQUE" }
 19             ]
 20         }
 21     }
 22 }
~                                                                                                                                                                             
~                                                                                                                                                                             
~

**Comment by lvca** [comment]
Thanks, fixed.

**Comment by zhuobao** [comment]
is this fix available in 2.1 development version? or just the github version?

**Comment by lvca** [comment]
2.1-SNAPSHOT. You can get snapshots from sonatype repo: https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.1-SNAPSHOT/
