### ISSUE TITLE
etl does not support creating bidirectional light weight edges - request for enhancement

### ISSUE THREAD

**Issue by anmoldeep0123** [orientechnologies/orientdb-etl#74]
Refer to this topic for more information : 

https://groups.google.com/forum/#!topic/orient-database/FOxNd-TTCvw

**Comment by lvca** [comment]
This is not necessary. I'm going to answer on that Topic.

**Comment by anmoldeep0123** [comment]
I saw the reply : 
"Use the "edge" transformer in ETL, not LINK."
 but using edge doesn't create a lightweight edge , I need to create bidirectional lightweight relations .

EDGE transformer --

joinFieldName OK 
direction - I don't need this :) 
class Edge's class name string false 'E'  - I do not want to do this :(
lookup - OK 
unresolvedLinkAction OK 

Please help 
thanks

**Comment by anmoldeep0123** [comment]
Please read the problem statement again . Thanks a lot .

**Comment by lvca** [comment]
Have you read the docs about http://orientdb.com/docs/last/Loader.html#orientdb ? Set **"useLightweightEdges": true** in configuration.

**Comment by anmoldeep0123** [comment]
Can the link transformer in orientDB ETL be enhanced to take INVERSE as an option key:value pair in the json .

Ref : http://orientdb.com/docs/last/SQL-Create-Link.html

INVERSE, tells to create the connection on the opposite direction. This is common when you've imported 1-N relationships from a RDBMS where they are mapped at the opposite direction .

If this enhancement can be done , it solves our purpose .

Regards 
Anmol
