### ISSUE TITLE
Suggestion : allow to specify index metadata in orientDB loader

### ISSUE THREAD

**Issue by padutilleul** [orientechnologies/orientdb-etl#87]
If you want to index NULL values in OrientDB, you have to specify ``METADATA {ignoreNullValues : false}`` when you define your index, but you can't do it with the ETL module.

Use case : 
Any request like ``SELECT FROM V WHERE property IS NULL`` need this to use an index

Suggestion : 
Accept the folowing syntax in the orientDB loader : 
```
"loader" : {
    "orientdb": {
      ...
      "indexes": [
        {"class":"V", "fields":["<key>:<key-type>"], "type":"NOTUNIQUE", "metadata": {
             "ignoreNullValues" : false
        } }
      ]
    }
  }
```

**Comment by robfrank** [comment]
There's merge from a pull request that implement this feature. 
Need to add a test and update the documentation

**Comment by robfrank** [comment]
add test, improve documentation.
