### ISSUE TITLE
Add enconding in source configuration

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb-etl#89]
In the "source" section add additional optional entry to define encoding:

```json
 "source" : {

    "file": { "path": "$filePath", 
     "lock" : true ,
    "encoding": "UTF-8"
  }
  },
```

**Comment by tschnoelzer** [comment]
thx!will do.(it was working the way you told me with multiline false... )bestTimo Roberto Franchini <notifications@github.com> hat am 9. September 2015 um 09:12 geschrieben:In the "source" section add additional optional entry to define encoding:"source" : {"file": { "path": "$filePath", "lock" : true },
"encoding": "UTF-8"
},—Reply to this email directly or view it on GitHub.
