### ISSUE TITLE
oetl.bat : command line configuration variables / parameters doesn't work 

### ISSUE THREAD

**Issue by nidaca** [orientechnologies/orientdb-etl#91]
In this moment there is a problem with etl 's command line configuration variables on Windows, they are not correctly passed to the OETLProcessor main class. The problem seems to be the following piece of script:

set CMD_LINE_ARGS=

:setArgs
if ""%1""=="""" goto doneSetArgs
set CMD_LINE_ARGS=%CMD_LINE_ARGS% %1
shift
goto setArgs

:doneSetArgs

which doesn't expand the command line correctly because in cmd the '=' sign (used in the parameters syntax) is considered a command line parameters delimiter, hence we will get wrong results in CMD_LINE_ARGS environment variable (which is later used as a command line for the java main class).

One possible solution to this is: set CMD_LINE_ARGS=%*       ... a solution equivalent to the one from oetl.sh shell script. Tested and working !

Thanks !

**Comment by robfrank** [comment]
I don't have a windows system to test it, but feel free to submit a pull request on develop branch, I'll be happy to merge.

**Comment by robfrank** [comment]
pr merged on develop, I will backport on 2.1.x

**Comment by lvca** [comment]
@robfrank Thanks. When back-ported, please update the milestone to 2.1.x ;-)

**Comment by nidaca** [comment]
10x for the quick feedback, will this (and #92 and #93) be back-ported also for 2.0.x branch ?

**Comment by robfrank** [comment]
Hi, I've just backported all to 2.0.x.

**Comment by nidaca** [comment]
Hi @robfrank, great news ... we are still using 2.0.x because of some dependencies.

**Comment by baltag** [comment]
Thanks, we are still using 2.0.x because of some dependencies!
