### ISSUE TITLE
Command line configuration variables / parameters only works when they have uppercase names

### ISSUE THREAD

**Issue by nidaca** [orientechnologies/orientdb-etl#92]
There is another problem with command line configuration variables, excepting the initial issue described here: https://github.com/orientechnologies/orientdb-etl/issues/91

... the issue is that the parameters works only if they have uppercase names.

Looking on the OETLProcessor code seems to be an inconsistency here, on this line, that generates the problem:
https://github.com/orientechnologies/orientdb-etl/blob/master/src/main/java/com/orientechnologies/orient/etl/OETLProcessor.java#L142

Why are command line configuration variables pushed uppercase in the variables context ?

Thank you !

**Comment by robfrank** [comment]
Hi, the fix is available on  develop and 2.1.x branch. Please close the issues if all is ok

**Comment by nidaca** [comment]
Hi, nicely done. I saw that in this moment etl will have cumulative configuration variables (besides the ones from the command line). For example you could have a config json (with only a 'config' section) and let's say another json with the transforming blocks, which is a nice feature. Will this feature remain as it is now (including the variables overriding policy) ? Closing this ...

**Comment by robfrank** [comment]
>For example you could have a config json (with a 'config' section only) and let's say another json with the transforming blocks, which is a nice feature. Will this feature remain as it is now (including the variables overriding policy) ?

Yes! it's an hidden feature! I will document it ASAP.
