### ISSUE TITLE
etl begin blocks executed twice

### ISSUE THREAD

**Issue by nidaca** [orientechnologies/orientdb-etl#93]
Another issue of the etl tool seems to be the double execution of the begin blocks. Looking on the OETLProcessor code seems that the following line generates this problem:

https://github.com/orientechnologies/orientdb-etl/blob/master/src/main/java/com/orientechnologies/orient/etl/OETLProcessor.java#L231

Thank you ... waiting for feedback !

**Comment by robfrank** [comment]
Hi, why do you think  that begin block are executed twice? The line is inside a for cycle that execute each begin  block in order.
Have you got a test case or even a json config with sample import files?

**Comment by nidaca** [comment]
Hi, because it is executed again in the execution methods, here:

https://github.com/orientechnologies/orientdb-etl/blob/master/src/main/java/com/orientechnologies/orient/etl/OETLProcessor.java#L434

The wrong execution statement (line 231) is located in the parse method which is only for parsing and configuring things, no execution needed there.

**Comment by robfrank** [comment]
Ok, thank you very much for your report, I'll work on that. 
If you  want to collaborate, feel free to submit PR on develop branch.

**Comment by robfrank** [comment]
Thank you for the report. I fixed on develop and 2.1.x branches. Please close the issue if all is ok.

**Comment by nidaca** [comment]
10x, closing it ...

**Comment by baltag** [comment]
Thanks, for fixing this.
